print("количество школьников = ")
n = int(input())
print("количество яблок = ")
k = int(input())
print("яблок досталось каждому = ")
z = int(k / n)
print (z)
print("яблок осталось в корзинке = ")
z = k % n
print (z)
